datasets:
  raw: data/raw/USCensus1990.data.txt
  processed:
    train: data/processed/USCensus1990_train.csv
    valid: data/processed/USCensus1990_valid.csv
    test: data/processed/USCensus1990_test.csv
  data_split:
    train: 0.6
    valid: 0.2
    test: 0.2

features:
  age_col: dAge
  citizen_col: iCitizen
  hour_col: dHour89
  gain_col: dIncome1
  cost_col: iFertil

  binary_cols:  # 5 cols
    - iMay75880
    - iRownchld
    - iRrelchld
    - iSept80
    - iVietnam

  categorical_cols: # 34 cols
    - iAvail
    - iClass
    - iDisabl1
    - iDisabl2
    - iEnglish
    - iLooking
    - iMeans
    - iMilitary
    - iMobility
    - iMobillim
    - iPerscare
    - iRagechld
    - iRelat1
    - iRelat2
    - iRemplpar
    - iRiders
    - iRlabor
    - iRPOB
    - iRvetserv
    - iSchool
    - iSubfam1
    - iSubfam2
    - iTmpabsnt
    - iWork89
    - iWorklwk
    - iYearsch
    - iYearwrk
    - dYrsserv
    - dIndustry # verified
    - dOccup
    - dDepart
    - dPoverty # (To be verified)
    - dPwgt1
    - dWeek89

  removed_cols: # 23 cols
    - dAncstry1 # Confounding variable
    - dAncstry2 # Confounding variable
    - dHispanic # Confounding variable
    - dHours  # Repeated with dHour89
    - iRPOB # Too many categories
    - dIncome2  # Repeated with dIncome1
    - dIncome3  # Repeated with dIncome1
    - dIncome4  # Repeated with dIncome1
    - dIncome5  # Repeated with dIncome1
    - dIncome6  # Repeated with dIncome1
    - dIncome7  # Repeated with dIncome1
    - dIncome8  # Repeated with dIncome1
    - iMarital  # Confounding variable
    - iOthrserv # Same value for all examples (verified)
    - dPOB  # Same value for all examples
    - dRearning # Repeated with dIncome1
    - dRpincome # Repeated with dIncome1
    - iRspouse  # Confounding variable
    - iFeb55  # Same value for all examples
    - iSex  # Same value for all examples
    - iWWII # Same value for all examples
    - iImmigr # Same value for all examples
    - iKorean # Same value for all examples

model:
  max_epochs: 3
  batch_size: 64
  learning_rate: 1e-4
  input_dim: 215
  hidden_dim: 128
  weight_decay: 1e-5
